#server:
#  port: 8086
#
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: continent
#          uri: lb://continent
#          predicates:
#            - Path=api/continent/**
#        - id: country
#            uri: lb://country
#            predicates:
#              - Path=/api/country/**
#
